# Generated by Django 3.1.2 on 2021-05-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.FloatField(choices=[(1.0, '*'), (2.0, '**'), (3.0, '***'), (4.0, '****'), (5.0, '*****')], default=0.0, verbose_name='Score'),
        ),
    ]
