# Generated by Django 3.1.2 on 2021-05-09 15:57

from django.db import migrations, models
import django.splice.splicefields


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment_synthesized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_taint',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='content_id_synthesized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='content_id_taint',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='creation_date_synthesized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='creation_date_taint',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='ip_address_synthesized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='ip_address_taint',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='score_synthesized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='score_taint',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='session_id_synthesized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='session_id_taint',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='user_email_synthesized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='user_email_taint',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='user_name_synthesized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='user_name_taint',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=django.splice.splicefields.SpliceTextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content_id',
            field=django.splice.splicefields.SplicePositiveIntegerField(blank=True, null=True, verbose_name='Content ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='creation_date',
            field=django.splice.splicefields.SpliceDateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ip_address',
            field=django.splice.splicefields.SpliceGenericIPAddressField(blank=True, null=True, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=django.splice.splicefields.SpliceFloatField(choices=[(1.0, '*'), (2.0, '**'), (3.0, '***'), (4.0, '****'), (5.0, '*****')], default=3.0, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='review',
            name='session_id',
            field=django.splice.splicefields.SpliceCharField(blank=True, max_length=50, null=True, verbose_name='Session ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_email',
            field=django.splice.splicefields.SpliceEmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_name',
            field=django.splice.splicefields.SpliceCharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
    ]
